project:
  type: website

website:
  title: "Jack Woodcock"
  search: false
  sidebar:
    style: "docked"
    title: "Jack Woodcock"
    logo: "assets/images/profile.jpeg"
    collapse-level: 2
    contents:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects & Publications
      - href: events.qmd
        text: Events
      - text: GitHub
        url: https://github.com/UoB-jack
        target: _blank
        rel: noopener noreferrer
      - text: Research profile
        url: https://research-information.bris.ac.uk/en/persons/jack-woodcock/
        target: _blank
        rel: noopener noreferrer
      - text: Practice-Oriented AI
        url: https://www.bristol.ac.uk/cdt/practice-oriented-ai/
        target: _blank
        rel: noopener noreferrer
      - text: Bristol Climate Dynamics Group
        url: https://www.climatebristol.org/
        target: _blank
        rel: noopener noreferrer

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
